//
//  Animal.swift
//  Fanimal
//
//  Created by Ariel Theodore W on 13/05/20.
//  Copyright © 2020 ariltw. All rights reserved.
//

struct Animal {
    var id: Int
    var location: String
    var name: String
    var image: String
    var type: TYPE
    var speed: Int
    var description: String
}

enum TYPE {
    case Bird
    case Reptiles
    case Fish
    case Mammals
    case Invertebrates
    
    var name: String {
        get { return String(describing: self) }
    }
}

var mock_animal: [Animal] = [
    Animal(id: 1, location: "Indonesia", name: "Komodo Dragon", image: "animal_1.jpg", type: TYPE.Reptiles, speed: 13, description: "The Komodo dragon (Varanus komodoensis), also known as the Komodo monitor, is a species of lizard found in the Indonesian islands of Komodo, Rinca, Flores, and Gili Motang.[5] A member of the monitor lizard family Varanidae, it is the largest extant species of lizard, growing to a maximum length of 3 metres (10 ft) in rare cases and weighing up to approximately 70 kilograms (150 lb)"),
    Animal(id: 2, location: "Africa", name: "Cheetah", image: "animal_2.jpg", type: TYPE.Mammals, speed: 75, description: "The cheetah (Acinonyx jubatus) is a large cat native to Africa and central Iran. It is the fastest land animal, capable of running at 80 to 128 km/h (50 to 80 mph), and as such has several adaptations for speed, including a light build, long thin legs and a long tail. Cheetahs typically reach 67–94 cm (26–37 in) at the shoulder, and the head-and-body length is between 1.1 and 1.5 m (3.6 and 4.9 ft). Adults typically weigh between 20 and 65 kg (44 and 143 lb). Its head is small, rounded, and has a short snout and black tear-like facial streaks. The coat is typically tawny to creamy white or pale buff and is mostly covered with evenly spaced, solid black spots. Four subspecies are recognised."),
    Animal(id: 3, location: "North America", name: "Peregrine Falcon", image: "animal_13.jpg", type: TYPE.Bird, speed: 242, description: "The peregrine falcon (Falco peregrinus), also known as the peregrine, and historically as the duck hawk in North America, is a widespread bird of prey (raptor) in the family Falconidae. A large, crow-sized falcon, it has a blue-grey back, barred white underparts, and a black head. The peregrine is renowned for its speed, reaching over 320 km/h (200 mph) during its characteristic hunting stoop (high-speed dive), making it the fastest bird in the world, as well as the fastest member of the animal kingdom. According to a National Geographic TV program, the highest measured speed of a peregrine falcon is 389 km/h (242 mph). As is typical for bird-eating raptors, peregrine falcons are sexually dimorphic, with females being considerably larger than males. According to one study, it has the fastest visual processing speed of any animal tested so far, and can register discrete changes up to 129 Hz or cycles per second."),
    Animal(id: 4, location: "Indian and Pacific Oceans", name: "Black Marlin", image: "animal_4.jpg", type: TYPE.Fish, speed: 82, description: "The black marlin (Istiompax indica) is a species of marlin found in tropical and subtropical areas of the Indian and Pacific Oceans. With a maximum published length of 4.65 m (15.3 ft) and weight of 750 kg (1,650 lb), it is one of the largest marlins and also one of the largest bony fish. It is one of the fastest fish species as well, having been recorded unwinding fishing line at 82 mph (120 ft/s). Black marlin are fished commercially and are also a highly prized game fish."),
    Animal(id: 5, location: "Oceans", name: "Loliginidae", image: "animal_5.jpg", type: TYPE.Invertebrates, speed: 22, description: "Loliginidae, commonly known as pencil squids, is an aquatic family of squid classified in the order Myopsida."),
    Animal(id: 6, location: "Pelagic Waters of Tropical and Subtropical Oceans Worldwide", name: "Yellowfin Tuna", image: "animal_6.jpg", type: TYPE.Fish, speed: 47, description: "The yellowfin tuna (Thunnus albacares) is a species of tuna found in pelagic waters of tropical and subtropical oceans worldwide.  Yellowfin is often marketed as ahi, from the Hawaiian ʻahi, a name also used there for the closely related bigeye tuna. The species name, albacares (white meat) can also lead to confusion: in English, the albacore tuna (Thunnus alalunga) is a different species, while yellowfin is officially designated albacore in French and referred to as albacora by Portuguese fishermen."),
    Animal(id: 7, location: "Africa", name: "Lion", image: "animal_7.jpg", type: TYPE.Mammals, speed: 50, description: "The lion (Panthera leo) is a species in the family Felidae; it is a muscular, deep-chested cat with a short, rounded head, a reduced neck and round ears, and a hairy tuft at the end of its tail. It is sexually dimorphic; adult male lions have a prominent mane, which is the most recognisable feature of the species. With a typical head-to-body length of 184–208 cm (72–82 in) they are larger than females at 160–184 cm (63–72 in). It is a social species, forming groups called prides. A lion pride consists of a few adult males, related females and cubs. Groups of female lions usually hunt together, preying mostly on large ungulates. The lion is an apex and keystone predator, although some lions scavenge when opportunities occur, and have been known to hunt humans, although the species typically does not."),
    Animal(id: 8, location: "Australia and South America", name: "Horse-fly", image: "animal_8.jpg", type: TYPE.Invertebrates, speed: 90, description: "Horse-flies or horseflies (for other names, see common names) are true flies in the family Tabanidae in the insect order Diptera. They are often large and agile in flight, and the females bite animals, including humans, to obtain blood. They prefer to fly in sunlight, avoiding dark and shady areas, and are inactive at night. They are found all over the world except for some islands and the polar regions (Hawaii, Greenland, Iceland). Both horse-flies and botflies (Oestridae) are sometimes referred to as gadflies."),
    Animal(id: 9, location: "All the Seas of the Earth", name: "Sailfish", image: "animal_9.jpg", type: TYPE.Fish, speed: 67, description: "A sailfish is a fish of the genus Istiophorus of billfish living in colder areas of all the seas of the earth. They are predominantly blue to gray in colour and have a characteristic dorsal fin known as a sail, which often stretches the entire length of the back. Another notable characteristic is the elongated bill, resembling that of the swordfish and other marlins. They are, therefore, described as billfish in sport-fishing circles."),
    Animal(id: 10, location: "Asia Pacific", name: "Tiger Beetle", image: "animal_10.jpg", type: TYPE.Invertebrates, speed: 4, description: "Tiger beetles are a large group of beetles, from the Cicindelinae subfamily, known for their aggressive predatory habits and running speed. The fastest known species of tiger beetle, Cicindela hudsoni, can run at a speed of 9 km/h (5.6 mph; 2.5 m/s), or about 125 body lengths per second. As of 2005, about 2,600 species and subspecies were known, with the richest diversity in the Oriental (Indo-Malayan) region, followed by the Neotropics."),
    Animal(id: 11, location: "Africa", name: "Springbok", image: "animal_11.jpg", type: TYPE.Mammals, speed: 55, description: "The springbok (Antidorcas marsupialis) is a medium-sized antelope found mainly in southern and southwestern Africa. The sole member of the genus Antidorcas, this bovid was first described by the German zoologist Eberhard August Wilhelm von Zimmermann in 1780. Three subspecies are identified. A slender, long-legged antelope, the springbok reaches 71 to 86 cm (28 to 34 in) at the shoulder and weighs between 27 and 42 kg (60 and 93 lb). Both sexes have a pair of black, 35-to-50 cm (14-to-20 in) long horns that curve backwards. The springbok is characterised by a white face, a dark stripe running from the eyes to the mouth, a light-brown coat marked by a reddish-brown stripe that runs from the upper fore leg to the buttocks across the flanks like the Thomson's gazelle, and a white rump flap."),
    Animal(id: 12, location: "Africa", name: "Black Mamba", image: "animal_12.jpg", type: TYPE.Reptiles, speed: 14, description: "The black mamba (Dendroaspis polylepis) is a species of venomous snake belonging to the family Elapidae. It is native to parts of sub-Saharan Africa. First formally described by Albert Günther in 1864, it is the second-longest venomous snake after the king cobra; mature specimens generally exceed 2 m (6 ft 7 in) and commonly grow to 3 m (9 ft 10 in). Specimens of 4.3 to 4.5 m (14 ft 1 in to 14 ft 9 in) have been reported. Its skin colour varies from grey to dark brown. Juvenile black mambas tend to be paler than adults and darken with age."),
    Animal(id: 13, location: "North America", name: "Pronghorn", image: "animal_3.jpg", type: TYPE.Mammals, speed: 55, description: "The pronghorn (UK: /ˈprɒŋhɔːrn/, US: /ˈprɔːŋ-/) (Antilocapra americana) is a species of artiodactyl (even-toed, hoofed) mammal indigenous to interior western and central North America. Though not an antelope, it is often known colloquially in North America as the American antelope, prong buck, pronghorn antelope, prairie antelope, or simply antelope because it closely resembles the true antelopes of the Old World and fills a similar ecological niche due to parallel evolution. It is the only surviving member of the family Antilocapridae."),
    Animal(id: 14, location: "North America, Europe, Asia", name: "Golden Eagle", image: "animal_14.jpg", type: TYPE.Bird, speed: 200, description: "The peregrine falcon (Falco peregrinus), also known as the peregrine, and historically as the duck hawk in North America, is a widespread bird of prey (raptor) in the family Falconidae. A large, crow-sized falcon, it has a blue-grey back, barred white underparts, and a black head. The peregrine is renowned for its speed, reaching over 320 km/h (200 mph) during its characteristic hunting stoop (high-speed dive), making it the fastest bird in the world, as well as the fastest member of the animal kingdom. According to a National Geographic TV program, the highest measured speed of a peregrine falcon is 389 km/h (242 mph). As is typical for bird-eating raptors, peregrine falcons are sexually dimorphic, with females being considerably larger than males. According to one study, it has the fastest visual processing speed of any animal tested so far, and can register discrete changes up to 129 Hz or cycles per second."),
    Animal(id: 15, location: "Atlantic, Pacific, and Indian Oceans", name: "Swordfish", image: "animal_15.jpg", type: TYPE.Fish, speed: 60, description: "Swordfish (Xiphias gladius), also known as broadbills in some countries, are large, highly migratory, predatory fish characterized by a long, flat, pointed bill. They are a popular sport fish of the billfish category, though elusive. Swordfish are elongated, round-bodied, and lose all teeth and scales by adulthood. These fish are found widely in tropical and temperate parts of the Atlantic, Pacific, and Indian Oceans, and can typically be found from near the surface to a depth of 550 m (1,800 ft). They commonly reach 3 m (9.8 ft) in length, and the maximum reported is 4.55 m (14.9 ft) in length and 650 kg (1,430 lb) in weight."),
    Animal(id: 16, location: "Asia", name: "White-throated Needletail", image: "animal_16.jpg", type: TYPE.Bird, speed: 105, description: "The white-throated needletail (Hirundapus caudacutus), also known as needle-tailed swift or spine-tailed swift, is a large swift in the genus Hirundapus. It is reputed to reach speeds of up to 170 km/h (105 mph) in horizontal flight, but this is unverified because the methods used to measure its speed have not been published."),
    Animal(id: 17, location: "Oceans", name: "Shortfin Mako Shark", image: "animal_17.jpg", type: TYPE.Fish, speed: 45, description: "The shortfin mako shark /ˈmɑːkoʊ/ (Isurus oxyrinchus), also known as the blue pointer or bonito shark, is a large mackerel shark. It is commonly referred to as the mako shark, as is the longfin mako shark (Isurus paucus). The shortfin mako is on record as the fastest-swimming shark, capable of bursts of speed up to 18.8 metres per second (68 km/h; 42 mph). The species is classified as Endangered by the IUCN."),
    Animal(id: 18, location: "Africa, Asia, Europe", name: "Eurasian Hobby", image: "animal_18.jpg", type: TYPE.Bird, speed: 100, description: "The Eurasian hobby (Falco subbuteo), or just simply hobby, is a small, slim falcon. It belongs to a rather close-knit group of similar falcons often considered a subgenus Hypotriorchis."),
    Animal(id: 19, location: "All Land", name: "Green Iguana", image: "animal_19.jpg", type: TYPE.Reptiles, speed: 22, description: "The green iguana (Iguana iguana), also known as the American iguana, is a large, arboreal, mostly herbivorous species of lizard of the genus Iguana. Usually, this animal is simply called the iguana. The green iguana ranges over a large geographic area; it is native from southern Brazil and Paraguay as far north as Mexico, and have been introduced from South America to Puerto Rico and are very common throughout the island, where they are colloquially known as gallina de palo (bamboo chicken or chicken of the trees) and considered an invasive species; in the United States, feral populations also exist in South Florida (including the Florida Keys), Hawaii, the U.S. Virgin Islands and the Rio Grande Valley of Texas."),
    Animal(id: 20, location: "Africa", name: "Wildebeest", image: "animal_20.jpg", type: TYPE.Mammals, speed: 50, description: "The wildebeest (/ˈwɪldɪbiːst/ WIL-dih-beest, /ˈvɪl-/ VIL-, plural wildebeest, wildebai or wildebeests), also called the gnu (/njuː/ NEW or /nuː/ NOO), is an antelope in the genus Connochaetes. It belongs to the family Bovidae, which includes antelopes, cattle, goats, sheep, and other even-toed horned ungulates. Connochaetes includes two species, both native to Africa: the black wildebeest or white-tailed gnu (C. gnou), and the blue wildebeest or brindled gnu (C. taurinus)."),
    Animal(id: 21, location: "Oceans", name: "Leatherback Sea Turtle", image: "animal_21.jpg", type: TYPE.Reptiles, speed: 21, description: "The leatherback sea turtle (Dermochelys coriacea), sometimes called the lute turtle or leathery turtle or simply the luth, is the largest of all living turtles and is the fourth-heaviest modern reptile behind three crocodilians. It is the only living species in the genus Dermochelys and family Dermochelyidae. It can easily be differentiated from other modern sea turtles by its lack of a bony shell, hence the name. Instead, its carapace is covered by skin and oily flesh."),
    Animal(id: 22, location: "Mexico", name: "Mexican Free-Tailed Bat", image: "animal_22.jpg", type: TYPE.Mammals, speed: 99, description: "The Mexican free-tailed bat or Brazilian free-tailed bat (Tadarida brasiliensis) is a medium-sized bat native to the Americas, regarded as one of the most abundant mammals in North America. Its proclivity towards roosting in huge numbers at relatively few locations makes it vulnerable to habitat destruction in spite of its abundance. The bat is considered a species of special concern in California as a result of declining populations. It has been claimed to have the fastest horizontal speed (as opposed to stoop diving speed) of any animal, reaching top ground speeds over 160 km/h; its actual air speed has not been measured. The Texas Legislature designated the Mexican free-tailed bat the state mammal (flying) in 1995."),
    Animal(id: 23, location: "Tropical and Subtropical Oceans", name: "Frigatebird", image: "animal_23.jpg", type: TYPE.Bird, speed: 95, description: "Frigatebirds (also listed as frigate bird, frigate-bird, frigate, frigate-petrel) are a family of seabirds called Fregatidae which are found across all tropical and subtropical oceans. The five extant species are classified in a single genus, Fregata. All have predominantly black plumage, long, deeply forked tails and long hooked bills. Females have white underbellies and males have a distinctive red gular pouch, which they inflate during the breeding season to attract females. Their wings are long and pointed and can span up to 2.3 metres (7.5 ft), the largest wing area to body weight ratio of any bird."),
    Animal(id: 24, location: "Australia", name: "Central Bearded Dragon", image: "animal_24.jpg", type: TYPE.Reptiles, speed: 25, description: "Pogona vitticeps, the central (or inland) bearded dragon, is a species of agamid lizard occurring in a wide range of arid to semiarid regions of Australia. This species is very popularly kept as a pet and exhibited in zoos."),
]
